FROM node:18.17.1-alpine3.18

ENV PORT 3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json /usr/src/app/
RUN npm install --legacy-peer-deps

ARG NEXT_PUBLIC_ENVIRONMENT
ARG NEXT_PUBLIC_BACKEND
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG NEXT_PUBLIC_CLUTCH_COMPANY_ID
ARG NEXT_PUBLIC_HR_EMAIL
ARG NEXT_PUBLIC_SALES_EMAIL
ARG REVALIDATE_TOKEN
ARG NEXT_PUBLIC_MAILER_LITE_API_TOKEN
ARG NEXT_PUBLIC_MAILER_LITE_BASE_URL
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_GTM_AUTH
ARG NEXT_PUBLIC_GTM_PREVIEW
ARG NEXT_PUBLIC_CDN_URL
ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_CLARITY_ID

ENV NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}
ENV NEXT_PUBLIC_BACKEND=${NEXT_PUBLIC_BACKEND}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV NEXT_PUBLIC_CLUTCH_COMPANY_ID=${NEXT_PUBLIC_CLUTCH_COMPANY_ID}
ENV NEXT_PUBLIC_HR_EMAIL=${NEXT_PUBLIC_HR_EMAIL}
ENV NEXT_PUBLIC_SALES_EMAIL=${NEXT_PUBLIC_SALES_EMAIL}
ENV REVALIDATE_TOKEN=${REVALIDATE_TOKEN}
ENV NEXT_PUBLIC_MAILER_LITE_API_TOKEN=${NEXT_PUBLIC_MAILER_LITE_API_TOKEN}
ENV NEXT_PUBLIC_MAILER_LITE_BASE_URL=${NEXT_PUBLIC_MAILER_LITE_BASE_URL}
ENV NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
ENV NEXT_PUBLIC_GTM_AUTH=${NEXT_PUBLIC_GTM_AUTH}
ENV NEXT_PUBLIC_GTM_PREVIEW=${NEXT_PUBLIC_GTM_PREVIEW}
ENV NEXT_PUBLIC_CAPTCHA_SITE_KEY=${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
ENV NEXT_PUBLIC_CLARITY_ID=${NEXT_PUBLIC_CLARITY_ID}


# add app
COPY . /usr/src/app

RUN npm run build

EXPOSE 3000

# start app
CMD ["npm", "start"]
