/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        'screen-xl-large': { max: '3840px' },
        'screen-large': { max: '2400px' },
        'screen-xxxl': { max: '1919px' },
        'screen-xxl': { max: '1440px' },
        'max-1390': { max: '1390px' },
        'max-1310': { max: '1310px' },
        'screen-xl': { max: '1200px' },
        'max-1100': { max: '1100px' },
        'max-1032': { max: '1032px' },
        'screen-xl-1': { max: '1199px' },
        'screen-lg': { max: '992px' },
        'screen-md': { max: '767px' },
        'screen-md+100': { max: '867px' },
        'screen-sm': { max: '576px' },
        'max-560': { max: '560px' },
        'screen-sm-100': { max: '476px' },
        'max-460': { max: '460px' },
        'max-400': { max: '400px' },
        'min-360': '360px',
        'min-sm': '576px',
        'min-md': '768px',
        'min-lg': '993px',
        'min-xl': '1201px',
        'min-1311': '1311px',
        'min-xxl': '1440px',
        'min-xxxl': '1920px',
      },
      colors: {
        'color-white': '#fff',
        borderGrey: '1px solid #f4f4f4',
        borderLight: '2px solid #effaff',
        borderBgBlue: '1px solid #eff7fe',
        borderWhite: '1px solid #fff',
        borderBlack: '1px solid #000',
        borderOrange: '1px solid #F47360',
        borderYellow: '1px solid #fee00c',
        gradient: 'linear-gradient(to bottom, #050E49, #25246e)',
        'color-blue-vr-microcase': '#172F85',
        'color-blue-banska-stiavnica': '#4D56F6',
        'color-blue-holokit': '#1A59B4',
        'color-blue-onix-ar': '#3736D0',
        'color-blue-unity-dsm': '#2E7EF5',
        'color-blue-unreal-space': '#358FEC',
        'color-blue-timescope': '#556EA7',
        'color-blue-cinematic-vr': '#1E3C72',
        'color-white6': '#F5F9FD',
        'color-black': 'rgb(0, 0, 0)',
        'color-light-gray2': '#E0E0E0',
        'color-light-gray3': '#E1E1E1',
        'color-yellow': '#FFB545',
        'color-cruise': '#B6EDEE',
        'color-pale-gray': '#F9F9F9',
        'color-dark-gray': '#504F53',
        'color-input-gray': '#F2F2F2',
        'color-grey-title': '#666666',
        lightBorder: 'rgba(255, 255, 255, 0.40)',
        lightBG: 'rgba(255, 255, 255, 0.20)',

      },
      boxShadow: {
        shadow: '0 10px 20px rgba(0, 0, 0, .1)',
        shadow2: '0 0 13px rgba(0, 0, 0, 0.1)',
      },
      fontFamily: {
        jakartaSans: ['var(--jakartaSans)', 'sans-serif'],
        main: ['var(--muktaVaani)', 'sans-serif'],
        arial: ['Arial', 'Helvetica', 'sans-serif'],
        montserrat: ['var(--montserratFont)', 'sans-serif'],
        openSans: ['var(--openSansFont)', 'sans-serif'],
        poppins: ['var(--poppinsFont)', 'sans-serif'],
        openSansPrimary: ['var(--openSans)', 'sans-serif'],
        generalSans: ['var(--generalSans)'],
        ibmPlexMono: ['var(--ibmPlexMono)'],
        jetBrains: ['var(--jetBrains)'],
        roboto: ['Roboto', 'Arial', 'sans-serif'],
        k2d: ['K2D', 'sans-serif'],
        openSansAlt: ['Open Sans', 'sans-serif'],
      },
    },
  },
  plugins: [
    import('tailwind-scrollbar-hide'),
  ],
};
