enum PageLinks {
  SERVICES = '/services',
  ELEARNING_DEVELOPMENT_SERVICES = '/elearning-development-services',
  TRAVEL_SOFTWARE_DEVELOPMENT_SERVICES = '/travel-software-development-services',
  HEALTHCARE_SOFTWARE_DEVELOPMENT_SERVICES = '/healthcare-software-development-services',
  SPORTS_AND_FITNESS_DEVELOPMENT_SERVICES = '/sports-and-fitness-development-services',
  LMS_DEVELOPMENT_SERVICES = '/lms-development-services',
  ONLINE_SCHEDULING_AND_BOOKING_SYSTEM = '/scheduling-and-booking-system-development-services',
  PRIVACY_POLICY = '/privacy-policy',
  WORK = '/work',
  BLOGS = '/blogs',
  SALESFORCE_PROCESS_AUTOMATION_CASE_STUDY = '/salesforce-process-automation-case-study',
  SALESFORCE_PERSONNEL_TRACKING_APP = '/salesforce-personnel-tracking-app',
  DEDICATED_TEAM_CALCULATOR = '/dedicated-team-calculator',
  WEB_DESIGN_AND_DEVELOPMENT = '/web-design-and-development',
  IOS_DEVELOPMENT = '/ios-development',
  ANDROID_APPLICATION_DEVELOPMENT = '/android-application-development',
  VR_AR_VIRTUAL_REALITY_AUGMENTED_REALITY_DEVELOPMENT = '/ar-vr-development-services',
  UI_UX_DESIGN_AND_DEVELOPMENT = '/ui-ux-design-and-development-services',
  THE_ONIX_STORY = '/the-onix-story',
  ABOUT_UKRAINE = '/about-ukraine',
  DEDICATED_TEAM = '/dedicated-team',
  JAMES_SMITH_ACADEMY_CASE_STUDY = '/james-smith-academy-case-study',
  MIPADDLE_CASE_STUDY = '/mipaddle-case-study',
  CONSTRUCTION_VR_MR = '/construction-vr-mr',
  CLUBHOUSE_CASE_STUDY = '/clubhouse-case-study',
  NOWWHAT_CASE_STUDY = '/nowwhat-case-study',
  HAAS_AUTOMATION_CASE_STUDY = '/haas-automation-case-study',
  PROJECT_X_CASE_STUDY = '/project-x-case-study',
  COLORADO_SPORTS_VIDEO_CASE_STUDY = '/colorado-sports-video-case-study',
  BRACKETOLOGY_CASE_STUDY = '/bracketology-case-study',
  PHLEX_CASE_STUDY = '/phlex-case-study',
  MISTERBNB_CASE_STUDY = '/misterbnb-case-study',
  DIGITAL_HEALTHCARE_AT_HOME_CASE_STUDY = '/digital-healthcare-at-home-case-study',
  BETTERME_CASE_STUDY = '/betterme-case-study',
  PHOTOWHY_CASE_STUDY = '/photowhy-case-study',
  EDPLUS_STUDY_CASE = '/edplus-study-case',
  BANSKA_STIAVNICA = '/banska-stiavnica',
  ONE_TOUCH_VR = '/one-touch-vr',
  TIMESCOPE = '/timescope',
  UNREAL_SPACE = '/unreal-space',
  UNITY_DSM = '/unity-dsm',
  MIXED_REALITY_HOLOKIT = '/mixed-reality-holokit',
  ONIX_AR_APP = '/onix-ar-app',
  INDUSTRIES = '/industries',
  PRODUCT_DISCOVERY = '/product-discovery',
  BRANDING_DESIGN = '/branding-services',
  BLOG_TOP_10_JAVA_MACHINE_LEARNING_TOOLS_AND_LIBRARIES =
  '/blog/top-10-java-machine-learning-tools-and-libraries',
  BLOG_ARTIFICIAL_INTELLIGENCE_IN_BANKING = '/blog/artificial-intelligence-in-banking',
  BLOG_HOW_TO_BUILD_A_FINTECH_APP_MUST_HAVE_FEATURES_COSTS =
  '/blog/how-to-build-a-fintech-app-must-have-features-costs',
  BLOG_FINDING_MEASURING_AND_MAINTAINING_PRODUCT_MARKET_FIT_FOR_A_SAAS_STARTUP =
  '/blogs',
  BLOG_WHAT_VR_PLATFORMS_ARE_BEST_FOR_GAME_DEVELOPMENT = '/blog/what-vr-platforms-are-best-for-game-development',
  BLOG_HOW_TO_BUILD_A_TRAVEL_MOBILE_APP =
  '/blog/how-to-build-a-travel-mobile-app',
  BLOG_AN_OVERVIEW_OF_TRAVEL_BOOKING_APIS_FOR_TRAVEL_AND_TOURISM_PROVIDERS =
  '/blog/travel-booking-apis-for-tourism-providers',
  BLOG_WHAT_DOES_IT_COST_TO_START_A_TRAVEL_BUSINESS_ONLINE
  = '/blog/what-does-it-cost-to-start-a-travel-business-online',
  BLOG_10_WAYS_AN_AUTOMATED_TRAVEL_SYSTEM_CAN_BENEFIT_A_TOURISM_BUSINESS =
  '/blog/how-to-build-automated-travel-system',
  BLOG_THE_IMPORTANCE_OF_DATA_SECURITY_IN_HEALTHCARE_SOFTWARE =
  '/blog/the-importance-of-data-security-in-healthcare-software',
  BLOG_MOBILE_APP_DEVELOPMENT_TRENDS = '/blog/mobile-app-development-trends',
  BLOG_HOTEL_BOOKING_APP_DEVELOPMENT_TIPS = '/blog/hotel-booking-app-development-tips',
  BLOG_THE_FEATURES_AND_BENEFITS_OF_HOTEL_PROPERTY_MANAGEMENT_SYSTEMS =
  '/blog/the-features-and-benefits-of-hotel-property-management-systems',
  BLOG_TOP_10_APPLICATIONS_OF_AR_AND_VR_IN_BUSINESS = '/blog/top-10-applications-of-ar-and-vr-in-business',
  BLOG_HOW_TO_CHOOSE_THE_RIGHT_TECH_STACK_FOR_MOBILE_APP_PART_ONE =
  '/blog/how-to-choose-the-right-tech-stack-for-mobile-app-part-one',
  WEBFLOW_DESIGN_AND_DEVELOPMENT_SERVICES = '/webflow-design-and-development-services',
  DIGITAL_PRODUCT_DESIGN_SERVICES = '/digital-product-design-services',
  MACHINE_LEARNING_DEVELOPMENT_SERVICES = '/machine-learning-development-services',
  SALESFORCE_DEV_SERVICES = '/salesforce-dev-services',
  FINTECH_SOFTWARE_AND_APP_DEVELOPMENT = '/fintech-software-and-app-development',
  BSTEVR_CASE_STUDY = '/bstevr-case-study',
  SOFTWARE_TESTING_QA_SERVICES = '/software-testing-qa-services',
  TRAVELBID_CASE_STUDY = '/travelbid-case-study',
  ART_UNITY = '/3d-game-art-development-services',
  UX_AUDIT = '/ux-audit-services',
  CROSS_PLATFORM = '/cross-platform-app-development',
  MOTION_DESIGN = '/motion-graphics-design-services',
  DEVOPS_SERVICES = '/devops-services',
  NATIONALS_HOLIDAYS = '/national-holidays-in-ukraine',
  CASE_STUDIES = '/case-studies',
  DESIGN_PORTFOLIO = '/design-portfolio',
  CAREERS = '/careers',
  MOTION_GRAPHICS_DESIGN_SERVICES = '/motion-graphics-design-services',
  GAME_ART_DEVELOPMENT_SERVICES = '/3d-game-art-development-services',
  INNERVR_CASE_STUDY = '/innervr-case-study',
  COSMETICS_ANALYSIS_AI_APP_CASE_STUDY = '/cosmetics-analysis-ai-app-case-study',
  STRIDIST_CASE_STUDY = '/stridist-case-study',
  ADORIC_CASE = '/adoric-case',
  CONTACT_US = '/contact-us',
  BLOG_6_CHATBOT_TRENDS_THAT_ARE_BRINGING_THE_FUTURE_CLOSER =
  '/blog/6-chatbot-trends-that-are-bringing-the-future-closer',
  BLOG_USES_CHATGPT_FOR_STARTUPS_GUIDE = '/blog/uses-chatgpt-for-startups-guide',
  BLOG_HEALTHCARE_CHATBOTS = '/blog/healthcare-chatbots',
  BLOG_VR_FOR_TRAINING = '/blog/vr-for-training',
  BLOG_HOW_TO_IMPLEMENT_VR_AND_AR_IN_FITNESS = '/blog/how-to-implement-vr-and-ar-in-fitness',
  BLOGS_TRAVEL = '/blogs/travel',
  BLOGS_VIRTUAL_AND_AUGMENTED_REALITY = '/blogs/virtual-and-augmented-reality',
  BLOGS_MACHINE_LEARNING = '/blogs/machine-learning',
  BLOGS_EDUCATION = '/blogs/education',
  BLOGS_FINTECH = '/blogs/fintech',
  BLOGS_SPORTS_AND_FITNESS = '/blogs/sports-and-fitness',
  LEARNING_POOL = '/learning-pool-case',
  VOLKSWAGEN = '/volkswagen-beetle-car-website-design-case-study',
  SPACE_NEWS = '/space-news-portal-design-case-study',
  SCHEDULER_FOR_MEDICAL_DOCTORS_CASE = '/scheduler-for-medical-doctors-case',
  REFERRAL_PROGRAM = '/referral-program',
  AI_IMAGE_CLASSIFICATION_SOLUTION_CASE_STUDY = '/ai-image-classification-solution-case-study',
  SAAS_MARKETING_PLATFORM_CASE_STUDY = '/saas-marketing-platform-case-study',
  BEAUTY_BOOKING_SERVICES_DESIGN_CASE_STUDY = '/beauty-booking-services-design-case-study',
  APPLICATION_MIGRATION_FROM_HEROKU_TO_AWS_CASE_STUDY = '/application-migration-from-heroku-to-aws-case-study',
  DEPLOYING_WORDPRESS_ON_KUBERNETES_CASE_STUDY = '/deploying-wordpress-on-kubernetes-case-study',
  WEBFLOW_WEBSITE_DESIGN_CASE_STUDY = '/webflow-website-design-case-study',
  HUNTER_ECOMMERCE_PLATFORM_DESIGN_CASE_STUDY = '/hunter-ecommerce-platform-design-case-study',
  FAYNO_MARKET_APP_CASE_STUDY = '/grocery-mobile-app-development-case-study',
  AI_FACE_REPLACING_SOLUTION_CASE_STUDY = '/ai-face-replacing-solution-case-study',
  CONVERT_CASE_STUDY = '/convert-case-study',
  CRYPTOCURRENCY_EXCHANGE_PLATFORM_CASE_STUDY = '/cryptocurrency-exchange-platform-case-study',
  MOBILE_APP_KEYBOARD_CASE_STUDY = '/mobile-app-keyboard-case-study',
  DUSCHOLUX_360_SHOWER_CASE_STUDY = '/duscholux-360-shower-case-study',
  CHINEASY_DESIGN_CASE_STUDY = '/chineasy-design-case-study',
  LSTM_NEWS_CATEGORIZER_CASE_STUDY = '/lstm-news-categorizer-case-study',
  NESTB_DESIGN_CASE_STUDY = '/nestb-design-case-study',
  FITNESS_COACHING_PLATFORM_DESIGN_CASE_STUDY = '/fitness-coaching-platform-design-case-study',
  COST_OPTIMIZATION_OF_PROJECT_INFRASTRUCTURE_CASE_STUDY = '/cost-optimization-of-project-infrastructure-case-study',
  WEBFLOW_WEBSITE_DEVELOPMENT_AND_DESIGN_FOR_GAMING_PRODUCTION_COMPANY =
  '/webflow-design-development-gaming-production-company-case-study',
  USABILITY_TESTING_DESIGN_CASE_STUDY = '/usability-testing-design-case-study',
  ANIMATED_CONCEPT_DIGITAL_AGENCY_DESIGN_CASE_STUDY = '/animated-concept-digital-agency-design-case-study',
  TRVLPAGE_DESIGN_CASE_STUDY = '/trvlpage-design-case-study',
  TRAVEL_MARKETPLACE_DESIGN_CASE_STUDY = '/travel-marketplace-design-case-study',
  SWITZERLAND_LIVING_COST_CALCULATOR_CASE_STUDY = '/switzerland-living-cost-calculator-case-study',
  BLOG_VIRTUAL_REALITY_MEETINGS = '/blog/virtual-reality-meetings',
  BLOG_USING_VIRTUAL_REALITY_FOR_MUSEUMS = '/blog/using-virtual-reality-for-museums',
  BLOG_DEVELOPING_MARINE_VR_SIMULATOR = '/blog/developing-marine-vr-simulator',
  BLOG_AR_VR_IN_MEDICAL_TRAINING = '/blog/ar-vr-in-medical-training',
  BLOG_HOW_MUCH_DOES_IT_COST_TO_USE_GPT_MODELS = '/blog/how-much-does-it-cost-to-use-gpt-models',
  BLOG_HAND_TRACKING_AND_GESTURE_RECOGNITION_USING_AI = '/blog/hand-tracking-and-gesture-recognition-using-ai',
  BLOG_HOW_TO_BUILD_AI_POWERED_MOBILE_APP = '/blog/how-to-build-ai-powered-mobile-app',
  BLOG_7_BASIC_SOFTWARE_DEVELOPMENT_MODELS_WHICH_ONE_TO_CHOOSE =
  '/blog/7-basic-software-development-models-which-one-to-choose',
  BLOG_WHY_ARE_OUTSOURCING_DEVELOPMENT_RATES_DIFFERENT_IN_UKRAINE =
  '/blog/why-are-outsourcing-development-rates-different-in-ukraine',
  BLOG_SUCCESSFUL_CASES_IN_SUPER_APPS_DEVELOPMENT = '/blog/successful-cases-in-super-apps-development',
  BLOG_HOW_TO_IMPLEMENT_QR_CODE_FOR_PAYMENTS = '/blog/how-to-implement-qr-code-for-payments',
  BLOG_INTRODUCTION_TO_CONSTRUCTION_APP_DEVELOPMENT = '/blog/introduction-to-construction-app-development',
  GOLF_LIVE_CASE_STUDY = '/online-golf-coaching-case-study',
  TESTIMONIALS = '/video-testimonials',
  SOLOMIYA = '/mental-health-app-development-case-study',
  BLOG_ML_IN_ECOMMERCE = '/blog/ml-in-ecommerce',
  BLOG_AI_IN_FOOTBALL = '/blog/ai-in-football',
  BLOG_VR_APP_DEVELOPMENT = '/blog/vr-app-development',
  PET_TRAVEL_PLATFORM_DEVELOPMENT_CASE_STUDY = '/pet-travel-platform-development-case-study',
  APARTMENT_RENTAL_CASE_STUDY = '/apartment-rental-company-website-case-study',
  CUSTOM_CRM_HEALTHCARE_INSURANCE_CASE_STUDY = '/custom-crm-healthcare-insurance-case-study',
  METRO_CASE_STUDY = '/metro-case-study',
  AGRICULTURE_INDUSTRY_WEBSITE_DESIGN_CASE_STUDY = '/agriculture-industry-website-design-case-study',
  APARTMENT_RENTAL_COMPANY_WEBSITE_CASE_STUDY = '/apartment-rental-company-website-case-study',
  LIVBOX_CASE_STUDY = '/creativity-management-app-case-study',
  INTERACTIVE_VR_MUSEUM_CASE_STUDY = '/interactive-vr-museum-development-case-study',
  KOZYSTAY_CASE_STUDY = '/apartment-booking-website-case-study',
  SAVII_CASE_STUDY = '/kids-banking-app-case-study',
  ANALYTICALS_CASE_STUDY = '/unified-data-analytics-platform-case-study',
  VYRA_CASE_STUDY = '/learning-platform-development-case-study',
  HEALTHCARE_PORTAL_CASE = '/healthcare-provider-portal-case-study',
  BLOGS_HEALTHCARE = '/blogs/healthcare',
  BLOGS_ECOMMERCE = '/blogs/ecommerce',
  BLOGS_ARTIFICIAL_INTELLIGENCE = '/blogs/artificial-intelligence',
}

export default PageLinks;
